
cluster: marius
token: <do token>
sshkey: /Users/thebes/.ssh/marius
max_threads: 10
coldkey: marius
machines:
  M0:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    script: "server.py"
    args: "--subtensor.network nakamoto --wandb.api_key <wandb token> --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilgpt2 --neuron.no_training"

  M1:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64    
    branch: metagraph_sync_fix
    script: "server.py"
    args: "--subtensor.network nakamoto --wandb.api_key <wandb token> --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilgpt2 --neuron.no_training"

  M2:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    script: "server.py"
    args: "--subtensor.network nakamoto --wandb.api_key <wandb token> --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name gpt2-medium --neuron.no_backward --neuron.no_training"

  M3:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    script: "server.py"
    args: "--subtensor.network nakamoto --wandb.api_key <wandb token> --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilgpt2"
  
  M4:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    script: "server.py"
    args: "--subtensor.network nakamoto --wandb.api_key <wandb token> --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilgpt2"

  M5:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    script: "server.py"
    args: "--subtensor.network nakamoto --wandb.api_key <wandb token> --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilgpt2"

  M6:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    script: "server.py"
    args: "--subtensor.network nakamoto --wandb.api_key <wandb token> --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilgpt2 --neuron.no_training"

  M7:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    script: "server.py"
    args: "--subtensor.network nakamoto --wandb.api_key <wandb token> --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilbert-base-uncased --neuron.no_backward"

  M8:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    script: "server.py"
    args: "--subtensor.network nakamoto --wandb.api_key <wandb token> --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name gpt2-medium --neuron.no_training --neuron.no_backward"

  M9:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    script: "server.py"
    args: "--subtensor.network nakamoto --wandb.api_key <wandb token> --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilbert-base-uncased"

  M10:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    script: "server.py"
    args: "--subtensor.network nakamoto --wandb.api_key <wandb token> --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilbert-base-uncased"

  
  M11:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    script: "server.py"
    args: "--subtensor.network nakamoto --wandb.api_key <wandb token> --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilbert-base-uncased --neuron.no_backward"

  M12:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    script: "server.py"
    args: "--subtensor.network nakamoto --wandb.api_key <wandb token> --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilbert-base-uncased --neuron.no_training --neuron.no_backward"

  M13:
    region: nyc1
    slug: s-4vcpu-8gb
    image: ubuntu-20-04-x64
    branch: metagraph_sync_fix
    script: "server.py"
    args: "--subtensor.network nakamoto --wandb.api_key <wandb token> --logging.debug --neuron.name $NAME --wandb.name $NAME --wandb.project marius --wandb.run_group $NAME --neuron.model_name distilbert-base-uncased --neuron.no_training"
      